spring:
  profiles.active: dev
---

spring:
    profiles: dev
    datasource:
        url: jdbc:h2:mem:shortenerDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
        username: sa
        password :
    jpa: 
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        generate-ddl : true
        hibernate.ddl-auto: update
        properties:
            hibernate.properties.hibernate.format_sql: true    
    h2:
        console.enabled: true
server:
    port: 8080
    
---

spring:
    profiles: test-unit
    datasource:
        url: jdbc:h2:mem:shortenerTestUnitDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
        username: sa
        password :
    jpa: 
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        generate-ddl : true
        hibernate.ddl-auto: update
        properties:
            hibernate.properties.hibernate.format_sql: true    
    h2:
        console.enabled: true
server:
    port: 8080
    
---

spring:
    profiles: production
    datasource:
      jndi-name: java:jboss/datasources/shortenerDBProd
      driverClassName: org.h2.Driver
      platform: H2      
server:
    port: 0